### ISSUE TITLE
I2C cable with adequate insulation gap

### ISSUE THREAD

**Issue by TurboNerd95** [Koepel/How-to-use-the-Arduino-Wire-library#3]
In regard's to this statement;

_"The I2C bus is a bus, so it can go through a cable".
The I2C bus was designed to be used on the same pcb board. The I2C bus is not meant to go through a cable. If wires or a short cable is used, then keep SDA away from SCL. The I2C bus can not handle crosstalk between SDA and SCL._

Is there a type of 2-core insulated data cable that exists, which can provide adequate separation between SDA and SCL, which you can recommend to us on the wiki? My first though could be coaxial cable, especially the old kind; https://qr.ae/pvuLBb

**Comment by Koepel** [comment]
There is theory and there is reality.

In theory, the line capacitance can be calculated, and that influences the maximum speed (together with the value of the pullup resistor). In real life, the line capacitance is the least problem.

Have you seen [UM10204.pfd](https://www.nxp.com/docs/en/user-guide/UM10204.pdf), page 54 ? As long as V<sub>DD</sub> is not too noisy, the power can be put in the middle.
Going further with that, it is possible to use a Cat5/6 cable and pair SDA with GND and pair SCL with GND and another pair for power (5V/3.3V with GND). If you need shielding, then use a shielded Cat5/6 cable. The clock speed has to be lowered, because of the increased line capacitance.

A old antenna cable (two wires with some distance) has also a inductive/capacitive coupling between the wires. That is not good. A coax cable for SDA and another coax cable for SCL is over the top.

In the end, the I2C is still a weak bus because the high level is made with pullup resistors. At some point, it is better to use RX-TX signals with or without RS-485. It depends on the noise level (motors, switching power modules, and so on) when the I2C bus is too weak for the project.

My induction cooker has a I2C bus for the buttons. There is a cable is 20cm long and the pcb boards are not in shielded cases. I think that a good quality industrial apparatus would not be designed like that.

**Comment by TurboNerd95** [comment]
Thank you for this! I think I am mostly clear on the wiring configuration using the CAT6 cable. However, are the 2 ground cable's that twist around the SDA and SDL line's supposed to be disconnected from the slave devices? (i.e. only connected at the master and floating at the slave?). I've seen this recommended for SPI and is called a star-point grounding pattern.

**Comment by Koepel** [comment]
When digital signals are put in a cable with multiple ground wires, then all the GND wires should be connected to GND at the start of the cable. Sometimes the GND of the signals are not connected at the end, only the power-GND is used.
When a current signal is used, then the GND wires carries the returning current (because of the twisted pair), so the GND should be connected at the end of the cable.

The I2C bus is in middle, because of the pullup resistor, there is a current of maximum 3mA.
I don't know what the best option is. I would start by connecting all the GND at the end. If they are all in a shielded cat5/6 cable, then there is no chance that a radio signal uses the GND wires as a ring-antenna.

You can see the twisted pair as a transformer. Send 3mA down a signal wire, and the other wire of the twisted pair will return 3mA, regardless how it is connected. This works better with higher frequencies. If you connect the GND at the Target (Slave) devices, then at least the GND wire has something to pull that 3mA from.
